require('dotenv').config();

module.exports = {
    development: {
        username: 'root',
        password: '12345',
        database: 'userstatus',
        host: 'localhost',
        dialect: 'mysql',
        timezone: '+07:00',
        logging: false,
        define: { freezeTableName: true },
    },
    test: {
        username: 'root',
        password: '12345',
        database: 'userstatus',
        host: 'localhost',
        dialect: 'mysql',
        timezone: '+07:00',
        logging: false,
        define: { freezeTableName: true },
    },
    docker_test: {
        username: process.env.DB_USERNAME || 'root',
        password: process.env.DB_PASSWORD || process.env.DB_PASS || '12345',
        database: process.env.DB_DATABASE || process.env.DB_NAME || 'userstatus',
        host: process.env.DB_HOST || 'mysql_db',
        dialect: 'mysql',
        timezone: '+07:00',
        logging: false,
        define: { freezeTableName: true },
    },
    production: {
        username: 'ud3v7y6suym75ol8',
        password: '0RYXqOnOj4wJquQ5nlrP',
        database: 'b6i7q5qabwnazzwabegz',
        host: 'b6i7q5qabwnazzwabegz-mysql.services.clever-cloud.com',
        dialect: 'mysql',
        timezone: '+07:00',
        logging: false,
        define: { freezeTableName: true },
        port: 21053,
    },
    buildlocal: {
        username: 'root',
        password: '',
        database: 'userstatus',
        host: '127.0.0.1',
        dialect: 'mysql',
        timezone: '+07:00',
        logging: false,
        define: { freezeTableName: true },
    },
};
